### ISSUE TITLE
SDLError: b'No available video device' on init

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/pysdl2-feedstock#11]
Issue:

pysdl2 breaks with latest sdl2 (2.0.9) in the following way (but works with 2.0.8):

$ conda create -n sdl2 pysdl2
$ conda activate sdl2
$ python
```
>>> import sdl2.ext
>>> sdl2.ext.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kai/miniconda/envs/sdl2/lib/python3.7/site-packages/sdl2/ext/common.py", line 44, in init
    raise SDLError()
sdl2.ext.common.SDLError: b'No available video device'
```
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/kai/miniconda/envs/sdl2:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
libxcb                    1.13              h14c3975_1002    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
pip                       19.1                     py37_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pysdl2                    0.9.6                 py37_1002    conda-forge
python                    3.7.3                h5b0a415_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
sdl2                      2.0.9                he1b5a44_1    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
sqlite                    3.26.0            h67949de_1001    conda-forge
tk                        8.6.9             h84994c4_1001    conda-forge
wheel                     0.33.1                   py37_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

XRef: https://github.com/conda-forge/sdl2-feedstock/issues/13
XRef2: https://github.com/vispy/vispy/pull/1634

ping: @djhoese @larsoner

**Comment by dschreij** [comment]
Thanks for reporting this @kmuehlbauer. Can you check if this issue also occurs if you install pysdl2 with pip? You might need to manually set the PYSDL2_DLL_PATH environment variable and point it to the sdl2 dll for it to work correctly. I'm curious if this problem is inherent to pysdl2 (it hasn't been updated in quite a while), your computer setup, or the conda build of pysdl2.

**Comment by dschreij** [comment]
Additionally, I see you use `py37_1002` of pysdl2. Can you see if version `py37_1` also gives this problem? It has recently been rebuilt using the azure CIs, and with sdl 2.0.9 as dependency. I don't expect it to matter much, but you never know.

**Comment by kmuehlbauer** [comment]
@dschreij Thanks for looking into this. Using `py37_1` errors in the same way. And same using the `pip` installed version of `pysdl2`.

**Comment by dschreij** [comment]
Then I'm afraid that the error lies within the source of pysdl2.  If I check https://pysdl2.readthedocs.io/en/rel_0_9_6/news.html then the latest version of pysdl2 (0.9.6) was built around sdl 2.0.6, so probably 2.0.9 contains some breaking changes. 

I recommend posting this issue on https://github.com/marcusva/py-sdl2/issues and let the developer of pysdl2 have a look at it. I'm leaving the issue open here for now too for reference.

Sorry for not being anymore help.

**Comment by dschreij** [comment]
You may also want to look at:
https://github.com/marcusva/py-sdl2/issues/77

> Not an issue of PySDL2 but SDL2 library itself, resp. conflict with xdm session security settings.

Are you working on Linux by any chance? It thus may have to do with yout xdm security settings.

**Comment by kmuehlbauer** [comment]
Yes, I'm on linux. I'll try to get help from the dev. Thanks!

**Comment by kmuehlbauer** [comment]
fixed by https://github.com/conda-forge/sdl2-feedstock/pull/15
