### ISSUE TITLE
Upgrade to PySDL2 0.9.6 for Python 3.6 support

### ISSUE THREAD

**Issue by pervognsen** [conda-forge/pysdl2-feedstock#4]
I've been using 0.9.6 directly from PyPI, specifically for its Python 3.6 support. It would be nice if this recipe was updated to reflect that. As far as I can tell, it should just be a matter of updating the PyPI URL and MD5 hash. I don't have experience building things directly from Conda recipes, but if you'd prefer, I can try to make this change myself and send a PR.

**Comment by dschreij** [comment]
Sorry, I've neglected these recipes for a while since I moved away from Python as my stack for the projects I worked on. I'm moving back soon though, so I see where I can update the SDL libs where necessary.

Does this new version of pysdl2 require SDL2 itself to be updated as well?
